# Generated by Django 4.0.3 on 2022-03-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productvariantprice_product_variant_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_image',
        ),
    ]
